### PR TITLE
Sensoris initial

### PR DESCRIPTION
**Pull request by rai20**
Initial commit for sensoris demo app that enables the transfer of GPS data.

Invehicle app = Depends on Boost 1.67 and Protobuf-cpp 3.6.1 Protobuf is a newly added dependency.
Cloud app = Depends on Protobuf-java 3.6.1 and https://github.com/TooTallNate/Java-WebSocket (v1.3.9)

### CODE REVIEW

**Comment by daschubert** [comment]
* Protobuf-java 3.6.1: Piggybacked -> CQ21202
* Java-WebSocket 1.3.9: Piggybacked -> CQ21203

I could piggyback Protobuf-cpp **3.5.1**. Would this also work for you?

**Comment by daschubert** [comment]
* Protobuf-cpp 3.6.1: Created CQ 21219

**Comment by rai20** [comment]
Tested on a local network and the apps works fine.
The Server has been deployed on the azure cloud but could not be tested because of some network settings. 
I think  PR can be merged once the CQs are through.

**Comment by daschubert** [comment]
* Protobuf-cpp 3.6.1 -> license_certified

**Pull request merged**
