### PR TITLE
Feature/traccar client

### PR DESCRIPTION
**Pull request by SebastianSchildt**
First version of Kuksa Traccar client to allow GPS tracking of KUKSA enabled assets. Works with gpsd and with primitie lat/lon only logs

Will include AGL packaging later (and maybe also bundle gpsd lib).

For now, no external code in repo

### CODE REVIEW

**Comment by rohoet** [comment]
CQ is not approved yet..

**Comment by rai20** [comment]
Hi,
Could you please mention the CQs that are open for this Pull Request?
Thanks!

**Comment by rohoet** [comment]
Its CQ#17770. There was an issue of deriving the version of gps3 v0.33.3. We're waiting for approval.

**Comment by bs-jokri** [comment]
@SebastianSchildt consider removing this branch

**Pull request merged**
